#+title: Rabbit & Steel Shadow Guide
#+author: Quoise
#+date: 2026-04-15

* Intro
Rabbit & Steel Shadow Class guide written primarily for v2.0.2.7. 

At the time of starting this guide, the author has 10 Multiplayer Lunar wins on Shadow, 0 SP Lunar Wins. Primarily, the recommendations
here are targetted at 4P Lunar and high WR/consistency.

This guide could not be made possible without the help of other players in mino_dev Discord.
# check to see if said players are okay with being mentioned in guide.

** Related Resources
Details of Shadow's kit can be found in:
- [[https://rns.miraheze.org/wiki/Shadow][Shadow | Rabbit & Steel Wiki (rns.miraheze.org)]]
- [[https://babit.gitlab.io/rns-definitions/characters/shadow/][Shadow abilities | Babit's Rabbit & Steel Definitions++ (babit.gitlab.io)]]
  + More accessible "gamecode" and numbers regarding R&S.

For latest available guides, see [[https://discord.com/channels/496640298844422149/1238375581486288916][Guides Catalogue maintained by Stagz | mino_dev Discord (discord.com)]]

# attributions and claims to not own used images of R&S Loot + Gems

* Changelog (Releases)
# likely first release at 0.1.0, given I don't feel confident in gem and item tiering

* Playstyle
** Base Kit
Maximum damage rotation would prioritize in order of availibility,
4312.

As a rule-of-thumb, N1/N4 and N2 have about the same hitbox horizontally.[fn:N2: diameter of N1 and N4 is 5% bigger than the length of N2.]

* Gems Tier List
- NX :: Normal (non-gem) variant of X ability

Tier placing prioritizes "lines" and WR consistency. Shadow, by gem design, should
always buy a gem first gem first shop, most are damage positive.

Newer players (avoiding leap pvp) can consider auto-buying S2 and G2; avoid O4.

If on Subterra Sanctum or Churchmouse Streets first stage, consider
G1, G4 or special gem.

** S: Auto-picks, damage now and scales, always synergistic
1. R4
2. S3
   
** A: Carries/versatile
1. R1
2. R2
3. S1
4. S4
5. S2
6. O2
7. G3
    
** B: Alternatives
1. E3[fn:E3:Emerald Special enables Shadow to take +GCD, buff and debuff items; G1 scaling.]
2. E1
3. G2[fn:G2:Garnet Secondary is risky DPS-wise without synergies or second gem.]
4. O1
5. O4
6. R3

** C: Niche; good immediate damage
1. G1
2. G4[fn:G4:Garnet Defensive is also good for pvp-ing items.]
3. E2[fn:E2:Emerald Secondary I rate low due to poor Shackle RNG and Lunar rotations; it can still carry.]

** D: Ultra-niche
1. O3[fn:O3E4:Opal Special and Emerald Defensive close too many future lines and don't do efficient damage at base kit.]
2. E4[fn:O3E4]

* Item Tier List

* Example Builds
